### ISSUE TITLE
Unexpected character ~

### ISSUE THREAD

**Issue by osresearch** [theacodes/kicanvas#101]
https://kicanvas.org/?github=https%3A%2F%2Fgithub.com%2Ffelixheld%2Fqspimux%2Fblob%2Fmaster%2Fqspimux%2Fqspimux.kicad_pcb

```
Error: Unexpected character at index 32069: ~
Context: 
    (pad ~ smd circle (at 0 0) (size 0.5 0.5) (layers F.Cu F.Mask)
```

It is an older version `(kicad_pcb (version 20171130) (host pcbnew "(5.1.0-rc2-47-g6eb84e42f)")`, so perhaps something has changed in the pcb file format since then.

**Comment by theacodes** [comment]
Yeah, the format changed a lot between 5 and 6, so KiCanvas doesn't support 5. We have a bug for showing better error messages for v5 and lower files.

**Comment by osresearch** [comment]
I figured it was something like that. I'll keep an eye on #34 then.  Thanks for writing such a useful tool!

**Comment by theacodes** [comment]
Of course!
