### ISSUE TITLE
Quality of life improvement about zoom in/out

### ISSUE THREAD

**Issue by tapir** [theacodes/kicanvas#12]
**Describe the bug**
I was using CTRL + Scroll to zoom in on the canvas and I accidentally moved the cursor to the parameters pane which changed the browser zoom level instead of canvas.

**To Reproduce**
1. Position your mouse cursor on the right pane
2. CTRL + Scroll
3. Changes the zoom level of the whole browser

**Expected behavior**
I think, since zoom in/out is such a core part of this tool, it shouldn't mess with the browser zoom level at all.

**Environment**
 - OS: Linux
 - OS vesion: Ubuntu 22.10
 - Browser: Chrome
 - Browser version: 112.0.5615.49
 - Additional info: N/A

**Comment by theacodes** [comment]
Closing in favor of #20, which aims to deal with pan/zoom more broadly
