### ISSUE TITLE
add footprints and symbols libraries visualisation

### ISSUE THREAD

**Issue by dbozec** [theacodes/kicanvas#13]
It would be nice to be able to explore footprints and symbols libs available on Github with KiCanvas
For example being able to navigate through https://github.com/KiCad/kicad-footprints and see what footprints look like

**Comment by theacodes** [comment]
This is already on the roadmap:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/250995/233672065-6f583fa1-0dc3-43b2-beb4-43477221e5fd.png">

I'm going to close this for the time being, but feel free to add any additional context or information you think would be useful for me or anyone who might stumble across this issue. :)
