### ISSUE TITLE
Text variables using component property references aren't expanded

### ISSUE THREAD

**Issue by thejpster** [theacodes/kicanvas#14]
File: https://github.com/Neotron-Compute/Neotron-Pico/blob/develop/Kicad/io_exp.kicad_sch

Kicad:

![image](https://user-images.githubusercontent.com/959887/233613037-00a656a1-39f8-42dd-a377-954d06aa0794.png)

Kicanvas:

![image](https://user-images.githubusercontent.com/959887/233613106-af3b9111-2a00-45e0-8be7-62d61235a1b5.png)

That UUID I believe refers to the resistor that is located nearby. Yeah, I could have just duplicated the value, and if the component changes the current calculation is wrong anyway. I was trying out features in KiCAD.

**Comment by theacodes** [comment]
related #18
