### ISSUE TITLE
Text in wrong place

### ISSUE THREAD

**Issue by thejpster** [theacodes/kicanvas#15]
Source: https://github.com/Neotron-Compute/Neotron-Pico/blob/develop/Kicad/bmc.kicad_sch

KiCad:

![image](https://user-images.githubusercontent.com/959887/233615220-8d4a8c7a-b6a2-4798-bc59-d12f467a1933.png)

KiCanvas:

![image](https://user-images.githubusercontent.com/959887/233615315-f06828d1-2261-4e9f-8b46-6c7c90ae13c7.png)

**Comment by roryjamesallen** [comment]
I've just experienced this and narrowed it down to text alignment (if you haven't already noticed this which you probably have) - Left aligned text renders accurately, but right also renders as left
