### ISSUE TITLE
Failed to load from Github or via Drag-n-Drop

### ISSUE THREAD

**Issue by bwshockley** [theacodes/kicanvas#16]
Hello - I can't seem to get kicancas.org to open my board.  I paste in the github link...and it sits.  I tried drag and drop, without luck.  I tried Firefox 112 and Chrome 112.0.5615.121 (64-bit).

My files are located here: https://github.com/bwshockley/FigPi

Am I just doing something wrong?

**Comment by arturo182** [comment]
See #5, try https://github.com/bwshockley/FigPi/tree/main and it should work :)

**Comment by bwshockley** [comment]
Thank you!, that worked.  :)
