### ISSUE TITLE
Hierarchical label positions change when returning to root sheet after entering subsheet

### ISSUE THREAD

**Issue by n42** [theacodes/kicanvas#19]
Tested on multiple projects, using the Luna files @ https://github.com/greatscottgadgets/luna/tree/main/hardware/rev0 as public reference that exhibits the issue.

Upon loading the project, everything looks fine, e.g.
![Screenshot from 2023-04-21 15-57-17](https://user-images.githubusercontent.com/1751421/233655855-90afab0f-922b-472b-81c9-e9d6d4c16dbe.png)

After entering a hierarchical sheet by either double clicking it or using the sheet nav, and then returning to the root (possibly parent in general) sheet, the hierarchical label positions get offset, like this:
![Screenshot from 2023-04-21 15-57-33](https://user-images.githubusercontent.com/1751421/233656131-0cccb581-7805-4257-bee3-9482df9c7559.png)

What's interesting is that repeating the same thing, i.e. again entering a sheet, then returning to root, seems to _toggle_ the position offset. I.e. doing it once gets you back to the original, correct, view. Then doing the same thing again causes the offset to reappear, and so on, seemingly reliably.

**Comment by theacodes** [comment]
Very weird, thanks for finding this! :)
