### ISSUE TITLE
Note on landing page clarifying whether designs are uploaded to a server

### ISSUE THREAD

**Issue by Muny** [theacodes/kicanvas#2]
**Is your feature request related to a problem? Please describe.**
On the landing page prompting for either a GitHub link or to upload KiCAD files, it's not immediately clear that the files are only handled by the client's web browser.

**Describe the solution you'd like**
I think it might be insightful to new users to let them know that their designs stay in their own browser. Of course, this would be more important for files uploaded than those downloaded from public GitHub repos. I haven't tried one, but I'm not sure how private GitHub repos would work in this regard.

**Comment by theacodes** [comment]
This is a great idea, thank you. :)
