### ISSUE TITLE
DNP attribute from Kicad 7 is not displayed

### ISSUE THREAD

**Issue by TomKeddie** [theacodes/kicanvas#22]
You probably know this already but I didn't see this in the known issues so it's worth including here.  Thanks for a cool tool.  Test project is public at https://github.com/TomKeddie/prj-pcb-experiments/tree/master/esp8266-plugpack

![Screenshot_2023-04-22_08-22-31](https://user-images.githubusercontent.com/4367175/233793041-9a550e2a-1517-4dd0-9725-0fc29a37f655.png)
![Screenshot_2023-04-22_08-22-14](https://user-images.githubusercontent.com/4367175/233793043-1f7e2928-af87-4861-af28-4c6c3953e1cc.png)

**Comment by theacodes** [comment]
This was implemented in 865706752
