### ISSUE TITLE
Some plated through-holes and all NPTH are missing on board view

### ISSUE THREAD

**Issue by CapnKernel** [theacodes/kicanvas#27]
https://kicanvas.org/?github=https%3A%2F%2Fgithub.com%2FCapnKernel%2Fled-tester%2Ftree%2Fmain

There are six holes that aren't rendering in the browser.

Plated through-holes: (137.4, 98.72) and (139.94, 98.72)
Non-plated through-holes: (104.38, 83.48), (145.02, 83.48), (104.38, 98.72) and (145.02, 98.72)

Wonderful project!

**Comment by CapnKernel** [comment]
![image](https://user-images.githubusercontent.com/527149/236589923-bb56a32e-b429-4e53-b1c4-a9972d298a03.png)

**Comment by theacodes** [comment]
Interesting! Thanks for letting me know.
