### ISSUE TITLE
Footprints containing multiple pads with the same number only render one.

### ISSUE THREAD

**Issue by cyber-murmel** [theacodes/kicanvas#33]
> The file you're trying to view. If you don't want the file to be public, let us know and we'll arrange for you to send it privately.

https://kicanvas.org/?github=https://github.com/simplexion/rtl872xd-dev-board/tree/main/source/rtl872xd-dev-board

> A screenshot of the file in KiCAD

will follow up

> A screenshot of the file in KiCanvas

the board page doesn't render anything for me as of now. was still working yesterday...

> A description of the issue

If a footprint has multiple pads with the same number (e.g. ground pads of coaxial connectors) only one of these pads gets filled.

**Comment by theacodes** [comment]
Thanks for letting me know!

**Comment by theacodes** [comment]
This turned out to be the same issue as #27, so it's been fixed!
