### ISSUE TITLE
Zones with only front & back copper layers are not rendered

### ISSUE THREAD

**Issue by jaseg** [theacodes/kicanvas#35]
This one is a doozy!

For reasons only a deity could ever understand, KiCad uses some extra special syntax *specifically* when a zone includes both the front and back copper layers, but no inner copper layers. Instead of the S-expression `(layers "F.Cu" "B.Cu")` as one would expect, we instead get `(layers "F&B.Cu")`. When inner layers are included, we get `(layers "F.Cu" "In1.Cu" ...` as one would expect. This is only a really random special case, and does not affect any other layer combinations or S-expression attributes.

This quirk is present in both KiCad 6 and 7 file formats. The offending source location in the S-Expression serializer is https://gitlab.com/kicad/code/kicad/-/blob/d563e5be14bbea97e63ff8352a6f1504cceb7438/pcbnew/plugins/kicad/pcb_plugin.cpp#L1338

As far as I can tell, this code affects zone formatting for both standalone zones in a board, and zones that are part of a footprint, in both instances including keepout zones. It looks like it will also affect pads inside footprints.

![Screenshot from 2023-07-05 16-53-29](https://github.com/theacodes/kicanvas/assets/136313/cdeabfaf-9e63-4a6a-b41d-9f44bf1b4580)
![Screenshot from 2023-07-05 16-53-40](https://github.com/theacodes/kicanvas/assets/136313/e8640bf2-3c38-4238-9af9-a0d311bcaea4)

**Comment by theacodes** [comment]
Thanks for the detailed report! I thought I had this case covered but maybe it got lost when I shuffled some stuff around. :)
