### ISSUE TITLE
variables in title block info not parsed in schematic or board view

### ISSUE THREAD

**Issue by putyn** [theacodes/kicanvas#36]
same as #17 title block info is displaying variables without parsing them first; issue both in schematic & board; repository with files [here](https://github.com/putyn/epaper/tree/main/epaper-breakout)

kicad
![image](https://github.com/theacodes/kicanvas/assets/1035189/c522b183-8c1d-4264-96bd-6731b291246f)
kicanvas
![image](https://github.com/theacodes/kicanvas/assets/1035189/874e1e8f-1e87-4c01-addf-be93e19bef4a)

**Comment by theacodes** [comment]
Fixed for this simple case via c51e67e.

**Comment by putyn** [comment]
that was fast! thanks. 
on last thing, maybe I am nit picking but on schematics with multiple heretical sheets, "Id:" usually displays sheet number/total number of sheets 😄 

example from kicad (4 sheets in total, including root, viewing sheet 2)
![image](https://github.com/theacodes/kicanvas/assets/1035189/3dc77db7-6994-434a-a926-8bcfab9ef7bd)

**Comment by theacodes** [comment]
Yup, that one is a known issue that requires a little more noodling.
