### ISSUE TITLE
Random behavior on input folder dragging (was Can't get it to do anything)

### ISSUE THREAD

**Issue by holmesrichards** [theacodes/kicanvas#37]
I am running Chrome Version 114.0.5735.198, OS is Linux Mint 21.1 Cinnamon.

If I drag and drop any `.kicad_pro` file onto `https://kicanvas.org/` I see one of two behaviors (I can't reproducibly get one or the other): Either nothing at all happens, or it opens an Open File dialog with the correct file name but pointing into the wrong folder, namely `~/Desktop`.

If I paste `https://github.com/holmesrichards/herovco/blob/main/Hardware/PCB/herovco/herovco.kicad_pro` and hit enter, nothing happens.

(Ah, I guess it wants a KiCad project folder, rather than the `kicad_pro` file. That was not clear. It says "Paste a GitHub link or drag & drop your KiCAD files", suggest it should more specifically tell you to paste a link to or drag and drop a KiCad project folder.)

**Comment by holmesrichards** [comment]
Er, no, still having trouble. I dragged and dropped a folder and had it open before, but now when I try the same thing it opens a new browser tab trying to open the folder as a Chrome tab.

**Comment by theacodes** [comment]
I'll have to double check the drop behavior for folders, and also we should be able to figure out the rest of your project files if you paste a URL to a kicad_pro file.

**Comment by holmesrichards** [comment]
The behavior seems quite random, sometimes dragging works and sometimes not. It may have to do with previous history of file opening in that tab? I don't know. Right now I can't get it to fail.
