### ISSUE TITLE
Alternative options for panning

### ISSUE THREAD

**Issue by Muny** [theacodes/kicanvas#4]
**Is your feature request related to a problem? Please describe.**
With my peripherals (standard mouse with single scroll wheel, and a keyboard), it seems the only way to pan is with the mouse wheel for up/down, and shift+mouse wheel for left/right. With my setup, at least, the panning seems to be very insensitive. At a moderate zoom level, it takes a good number of wheel rotations for me to reach either side of the page.

**Describe the solution you'd like**
I think the insensitivity is okay for close-up movements, but it might be nice to have faster ways to pan. I haven't tried, but I would guess that currently a touchpad on a laptop might provide a better panning experience. 

My suggestion would be to add either right- or middle-mouse + drag panning (with an implementation similar to that of KiCAD's).

**Comment by theacodes** [comment]
Closing in favor of #20, which aims to deal with pan/zoom more broadly
