### ISSUE TITLE
CD4093 symbol is strange

### ISSUE THREAD

**Issue by holmesrichards** [theacodes/kicanvas#40]
https://github.com/holmesrichards/yash/tree/main/Hardware/PCB

KiCad:

![image](https://github.com/theacodes/kicanvas/assets/56895621/cd76dde4-dbec-43bf-b4e4-41d36a80f5e1)

KiCanvas:

![image](https://github.com/theacodes/kicanvas/assets/56895621/cdef90f0-9015-4505-bb7c-37308ee4caa2)

Only half filled, and seems to have AND and OR shapes superimposed.

**Comment by theacodes** [comment]
Thanks!

**Comment by jaseg** [comment]
This is KiCad's "demorgan" style feature. I think this feature is a bit disgraced by now, it's not used for new symbols anymore and I guess it will be removed at some point. Currently, a symbol can contain multiple units in each of multiple "demorgan" styles. During rendering, the unit for the selected style has to be super-imposed with special, common "global" units. The 40xx library has a lot of these, but there is a handful of such symbols scattered around other libraries as well.

**Comment by theacodes** [comment]
@jaseg thanks for the lead!

Commit 9613b96 adds support for De Morgan body styles, however, there's another bug here in that arcs with fills aren't rendered correctly. I'll have to fix that before I can mark this complete.

<img width="496" alt="image" src="https://github.com/theacodes/kicanvas/assets/250995/809ea9c5-67cb-4a4d-9150-ca68837a382c">
