### ISSUE TITLE
Non-alpha characters not shown properly 

### ISSUE THREAD

**Issue by CapnKernel** [theacodes/kicanvas#43]
Example project:

  https://kicanvas.org/?github=https%3A%2F%2Fgithub.com%2FCapnKernel%2Fpogoprog

Several of the pins have `{slash}` in the name, rather than this being interpreted and shown as `/`.

It seems that KiCad can store non-alpha characters using some sort of `{}` encoding.  KiCanvas doesn't know about this.

Pic from KiCad 7:

![image](https://github.com/theacodes/kicanvas/assets/527149/183da9cf-b046-4c68-af37-b0c4d1ae7327)

Pic from KiCanvas:

![image](https://github.com/theacodes/kicanvas/assets/527149/422e1e56-9952-4e69-b4ad-791ec21c845c)

Note that the `D0/RX` and `D1/TX` pins are shown correctly because KiCad is storing these as `/` not `{slash}`.

**Comment by theacodes** [comment]
Interest, we should be handling these [here](https://github.com/theacodes/kicanvas/blob/main/src/kicad/common.ts#L18), I'll see where the disconnect is.
