### ISSUE TITLE
kicanvas.js has a syntax error in Safari 16.2 (17614.3.7.1.7, 17614)

### ISSUE THREAD

**Issue by ianh** [theacodes/kicanvas#49]
**Describe the bug**
All kicanvas.org pages appear as a blank white page on my version of Safari, including the home page.

Looking at the JS console, the following error appears:

    [Error] SyntaxError: Unexpected token '{'
    	(anonymous function) (kicanvas.js:1)

**Expected behavior**
On Firefox, the page appears as expected.  It's just Safari that shows the behavior.

**Environment**
OS: macOS Monterey 12.6.2 (21G320)
Browser: Safari 16.2 (17614.3.7.1.7, 17614)

**Comment by theacodes** [comment]
Odd, maybe some weirdness when I upgraded to TypeScript 5.2

**Comment by theacodes** [comment]
This appears to be resolved in Safari 17, closing.
