### ISSUE TITLE
Root GitHub URLs do not load as expected

### ISSUE THREAD

**Issue by arturo182** [theacodes/kicanvas#5]
I'm not sure if this is on purpose, please excuse me and close the issue if it is.

If you have KiCad files in the root folder of your repo and you just paste the repo URL in KiCanvas (for example https://github.com/arturo182/serpente_hw), it doesn't open it. The console says "No valid KiCAD files found".
You need to explicitly specify the branch for it to work (for example https://github.com/arturo182/serpente_hw/tree/master/).

There was also no feedback after I pasted the first link, it took me a second to realize what was the problem.

**Comment by theacodes** [comment]
Looks like we can use `HEAD` to refer to the default branch, avoiding the need to make an API call to determine the default branch: https://github.com/arturo182/serpente_hw/tree/HEAD
