### ISSUE TITLE
KiCanvas won't load if a component value doesn't have a digit before a decimal point

### ISSUE THREAD

**Issue by CapnKernel** [theacodes/kicanvas#51]
https://github.com/pypilot/pypilot_schematics/tree/master/midpower_controller

Error: Unexpected character at index 113845: .
Context: 
    (fp_text value .1uF (at 2.5 2.56 270) (layer F.Fab)

**Comment by theacodes** [comment]
Is this a KiCAD 5 project? KiCanvas only works for KiCAD 6+ projects.

**Comment by CapnKernel** [comment]
Ok yes, seems it's a KiCad 5 project.  Perhaps it's better to say that than die, though.

**Comment by theacodes** [comment]
Indeed, we've got #34 to track that. :)
