### ISSUE TITLE
Desktop Safari support

### ISSUE THREAD

**Issue by dpharris** [theacodes/kicanvas#6]
**Describe the bug**
Window remains blank

**Expected behavior**
Show open to face page.

**Screenshots**
Blank screen

**Environment**

 - OS: OSX  
 - OS version: Ventura M2 laptop
 - Browser:  Safari
 - Browser version:
 - Additional info: 

**Additional context**

**Comment by gregsadetsky** [comment]
This also concerns iOS -- nothing is displayed at all on a phone accessing kicanvas.org

**Comment by theacodes** [comment]
Safari should be shipping support for that soon, so I'll see where things are when I'm able to come back to this. :)

**Comment by mengstr** [comment]
For me it works just fine now.  Running Safari 16.5.1 (18615.2.9.11.7) on Ventura 13.4.1

**Comment by theacodes** [comment]
Yeah, looks like this one is fixed. :)
