### ISSUE TITLE
Rendering colored texts in schematic viewer

### ISSUE THREAD

**Issue by JuYanYan** [theacodes/kicanvas#69]
The schematic text of KiCad7 can be changed in color. For colored text, the schematic as the following.

```plaintext
(text "Text Red" (at 142.24 91.44 0)
  (effects (font (size 1.27 1.27) (color 255 0 0 1)) (justify left bottom))
  (uuid 3a37bece-0dd8-43e0-9b9b-47f82af69158)
)
```

The color attribute is in the sub expression of font.

## KiCad Behaviors

KiCad renders the text of a specified color to a specific color simply. And that has no effect on changing the theme. For a transparent text, it will blend with the background color. For unassembled symbols, they will still be rendered in gray with their field colors specified.

## A possible implementation

#69 is a possible implementation.

**Comment by XiangYyang** [comment]
Implemented in #70
