### ISSUE TITLE
Pointer events on Android Chrome not working for pan/zoom

### ISSUE THREAD

**Issue by benjamind** [theacodes/kicanvas#7]
**Describe the bug**
Touch inputs via Pointer events API on Android Chrome doesn't appear to pan and zoom the viewport.

**To Reproduce**
1. Go to any schematic using and Android Chrome browser
2. Try to pinch zoom or pan the viewport 

**Expected behavior**
Pinch and pan zoom behaviors should work.

**Screenshots**

**Environment**
Android Chrome 112

**Additional context**

**Comment by theacodes** [comment]
Closing in favor of #20, which aims to deal with pan/zoom more broadly
