### ISSUE TITLE
Web component please?

### ISSUE THREAD

**Issue by benjamind** [theacodes/kicanvas#8]
**Is your feature request related to a problem? Please describe.**
An embeddable `<ki-canvas>` tag would be awesome!

**Describe the solution you'd like**
CDN bundled es module delivering a Custom Element for the viewer experience would be amazing. E.g.

```
<script src="http://kicanvas.org/embed.min.js" type="module"></script>
<ki-canvas href="http://myschematic.com/thingie.kicad_sch"><ki-canvas>
```

**Describe alternatives you've considered**
Image or script based embed would work for some use cases but would not have as much utility.

**Additional context**
This thing is fantastic and I am so happy to see you being it into reality!

**Comment by arturo182** [comment]
This is already mentioned in the roadmap (https://github.com/theacodes/kicanvas#status-and-roadmap), in the FAQ (https://github.com/theacodes/kicanvas#faq), and in the announcement blog (https://blog.thea.codes/introducing-kicanvas/).
![image](https://user-images.githubusercontent.com/249082/233611142-798622df-9b53-43cc-96d2-7ca3c604427b.png)
![image](https://user-images.githubusercontent.com/249082/233611340-55b39301-6101-411e-bb23-e8cd2c10699e.png)

![image](https://user-images.githubusercontent.com/249082/233611292-2104dc21-50a0-4f5c-84ad-9d0bcb221cce.png)
