### ISSUE TITLE
No valid KiCAD files found in project  

### ISSUE THREAD

**Issue by ar1a** [theacodes/kicanvas#9]
Hiya! Trying to get kicanvas to have a look at my (relatively simple? i think) project and it won't show up! Maybe this stems from a mishmash of kicad 6/7,  or maybe something else!

Anyways,
https://github.com/ar1a/sharkpad-rev2

Link that breaks: https://kicanvas.org/?github=https%3A%2F%2Fgithub.com%2Far1a%2Fsharkpad-rev2

**Comment by ar1a** [comment]
Sorry, the full error is
```
canvas.js:1619 Error: No valid KiCAD files found in project
    at pR.load_default_file (kicanvas.js:1619:1546)
    at pR.setup_project (kicanvas.js:1619:1131)
    at async HTMLInputElement.<anonymous> (kicanvas.js:1619:861)
```

**Comment by danielkucera** [comment]
I have the same:
![image](https://user-images.githubusercontent.com/1734256/233558478-27dc9e7e-0132-46b9-9929-891d110576ce.png)

**Comment by danielkucera** [comment]
uhm, it has to be a direct link to a file, now it works:

![image](https://user-images.githubusercontent.com/1734256/233559910-b7b442bc-9315-4053-b69c-5842cbd757ee.png)

I think it needs some better description.
