### ISSUE TITLE
Schematic print

### ISSUE THREAD

**Issue by mengstr** [theacodes/kicanvas#90]
Is there a way to print the schematic or layout without all the miscellaneous info and graphics elements around the image?  I'm mostly interested in printing the schematic - and it would be great if the background then was  #ffffff and not some off white color that just end up in a dirty background on the printer.  I guess a switch that made it monochrome would be ideal (at least for me that still are using a oldskool b/w laser printer ^__^ ) 

Anyho, I still love this project .....

**Comment by theacodes** [comment]
This would be a great feature to add in the future, I'll keep it in mind. :)
