### ISSUE TITLE
Can't open a .kicad_sch file

### ISSUE THREAD

**Issue by RaphTronic** [theacodes/kicanvas#95]
Tried to open the attached file (link below) advertised as being of .kicad_sch type. Got it from here: https://github.com/SolderedElectronics/Ozone-sensor-MQ131-breakout-with-easyC-hardware-design/tree/main/CAD/V1.1.1

Steps:
* Dragged and dropped into Firefox (Windows10), nothing happened
* Created a Github repository, uploaded the Zip file there, pasted the link in https://kicanvas.org, nothing happened

[MQ131 Soldered schematics MQ Breakout.zip](https://github.com/user-attachments/files/17346628/MQ131.Soldered.schematics.MQ.Breakout.zip)

Not critical at all as I do not need to edit, just need viewing and found the PDF.
So, just FYI.

**Comment by theacodes** [comment]
This seems to open fine in KiCanvas. Did you try opening the `.zip` with KiCanvas? If so, that won't work.
